### ISSUE TITLE
Fix the memory issues

### ISSUE THREAD

**Issue by psci2195** [psci2195/ffans#83]
@idimon4uk: you said that there is a memory (leak?) issue after the commit:
https://github.com/psci2195/ffans/commit/4fe99dcde72c314e4a5a2cdf26b1441dc614c82e

Please, either fix or add an .ini file switch to on/off this functionality..

**Comment by idimon4uk** [comment]
fixed on  Latest commit 532a044

**Comment by psci2195** [comment]
@idimon4uk : thanks for your contribution / merged!
