### ISSUE TITLE
Correct the random direction algorithm (solid angle based)

### ISSUE THREAD

**Issue by psci2195** [psci2195/ffans#84]
Currently: `theta_0 = (*var_uni)() * pi;`
Should be `costheta0=(*var_uni)() * 2.0 - 1.0` (costheta0 is juat a name of the variable!)
and, also, `sintheta0=sin(acos(costheta0))`

The `phi_0` functionality is correct and should not be fixed.

**Comment by idimon4uk** [comment]
Compleated commit 4e6052a

**Comment by psci2195** [comment]
@idimon4uk thanks, that is correct.
The CI build is also good: https://ci.appveyor.com/project/psci2195/ffans/build/1.0.37

**Comment by psci2195** [comment]
@idimon4uk : could I merge the branch `pieces-analysis`?

**Comment by psci2195** [comment]
or just this commit?

**Comment by idimon4uk** [comment]
yes, u could !

**Comment by psci2195** [comment]
@idimon4uk thanks for your contribution. Merged https://github.com/psci2195/ffans/pull/89.
